### ISSUE TITLE
Barre chord being wrongly drawn

### ISSUE THREAD

**Issue by amargs** [rluetzner/ChordImageGenerator#6]
I think a bug was introduced when enabling the barre option. Previously, if I used this fret position: x46464, it would generate this chord image:

![image](https://github.com/rluetzner/ChordImageGenerator/assets/17692221/289c60a2-931e-4425-a0dc-9c7dc2d11883)

Now, enabling the full barre draws this:
![image](https://github.com/rluetzner/ChordImageGenerator/assets/17692221/33f8ec34-fa69-4481-b360-1bac1d8f45c0)

And disabling it, it draws this:
![image](https://github.com/rluetzner/ChordImageGenerator/assets/17692221/18a4b5fc-0525-49b1-b15d-c96f3400aef8)

I believe the 6th fret notes should not be drawn as a barre, since in this case it would mean the 3rd string would also be pressed on the 6th fret which is not intended.

**Comment by Kernix13** [comment]
Also, that chord shape is a C#7 or Db7 but the `o` makes it seem that it is a fully diminished 7th chord which it is not. Also, what is 121311? Are they fingerings? But the 6th string has an "X" meaning it is not to be played.

**Comment by Kernix13** [comment]
If it helps, I have a guitar chord namer app that requires a user to enter the fret numbers and has options for sharp vs. flat keys and for different tunings. The defaults are Sharp (#) and Standard Tuning (E-A-D-G-B-e). My [Guitar Chord Namer](https://everyguitarchord.com/what-chord-is-this.html) is one of my portfolio projects. You could use it to make sure you have the correct chord name.

**Comment by rluetzner** [comment]
I'm very sorry for the late response. For whatever reason I didn't get any notification about this issue. I just noticed it today.

I'll look into it and get back to you.

**Comment by rluetzner** [comment]
@amargs , so as @Kernix13 also writes

> what is 121311? Are they fingerings? But the 6th string has an "X" meaning it is not to be played.

the fingerings are wrong. The app doesn't determine _optimal_ finger positions itself, but rather relies on you to set them correctly. If you do, you'll get this image (I didn't bother with the chordname):

![image](https://github.com/rluetzner/ChordImageGenerator/assets/14924663/23ff04c5-d508-4903-a148-abb0ae3dad87)

. Here's a link so you can verify it yourself: https://chordgenerator.luetzners.de/#D.png?p=x46464&f=-12131&s=2&b=false

I hope that helps. Thanks for using Chordgenerator. :slightly_smiling_face:

**Comment by rluetzner** [comment]
I assume that this is no longer an issue, so I'll close this ticket for now.
